public class calculator{

   public integer dozen;
   Public integer hafdozen;
   
   public decimal dozen1;
   Public decimal hafdozen1;
    
    
    public integer iadd ()
    {
    
        integer dozen = 12;
       integer hafdozen = 6;
    
     return dozen + hafdozen;
    }
    
    
    public decimal badd ()
    {
    
        decimal dozen1 = 12.6;
        decimal hafdozen1 = 6.3;
    
     return dozen1 + hafdozen1;
    }
    
  
}