Public class calinterface implements calculationinterface {

      public Integer addition(Integer val1 , Integer val2){
          
          return val1 + val2;
      
      }
      
      public Integer sub(Integer val1 , Integer val2){
      
          return val1 - val2;
      }
      
      Public Integer division(Integer val1 , Integer val2){
          
          return val1/val2;
      }
      
}