public class ssh_params_sh
{
/*
export sbl_connectstring=SIEBEL@SIEBDEV/FGBSBL123
export iniown_connectstring=FGB_INT@SIEBDEV/fgb123$
export bin_path=/siebel/FGB_R0/bin
export data_path=/siebel/FGB_R0/data
export IFBPATH=/siebel/FGB_R0/ifb/
export EIM_LOG_PATH=/siebel/ses/siebsrvr/enterprises/FGB_SBLDEV/FGB_DEVSVR01/log
export R2PATH=/siebel/FGB_R0
export ORACLE_BASE=/oracle/app/oracle/product/11.2.0
export ORACLE_HOME=/oracle/app/oracle/product/11.2.0/client_1
export PATH=$PATH:$ORACLE_HOME/bin
export param_gateway=172.20.219.56:2320
export param_enterprise=FGB_SBLDEV
export param_user=EIM_USER
export param_password=EIM_USER
export param_server=FGB_DEVSVR01
export log_path=/siebel/FGB_R0/logs
export src_path=/siebel/FGB_R0/sql
export siebsrvr_path=/siebel/ses/siebsrvr
export gateway_srvr_path=/siebel/ses/gtwysrvr
export BULK_LEAD_IP_DIR=/Siebel/Siebfile/Siebfile/SblIntegration/BULK_LEAD_IN
export BULK_LEAD_ARCH_DIR=/Siebel/Siebfile/Siebfile/SblIntegration/BULK_LEAD_ARCH
export BULK_SMS_LEAD_IP_DIR=/Siebel/Siebfile/Siebfile/SblIntegration/BULK_LEAD_IN
export BULK_SMS_ARCH_DIR=/Siebel/Siebfile/Siebfile/SblIntegration/BULK_LEAD_ARCH
export CSF_IP_DIR=/Siebel/Siebfile/Siebfile/SblIntegration/CSF_IN
export CSF_ARCH_DIR=/Siebel/Siebfile/Siebfile/SblIntegration/CSF_ARCH
export BDU_CUST_IP_DIR=/Siebel/Siebfile/Siebfile/SblIntegration/BDU_CUST_IN
export BDU_CUST_ARCH_DIR=/Siebel/Siebfile/Siebfile/SblIntegration/BDU_CUST_ARCH
export SWIFT_CODE_IN_DIR=/Siebel/Siebfile/Siebfile/SblIntegration/SWIFT_CODE_IN
export SWIFT_CODE_ARCH_DIR=/Siebel/Siebfile/Siebfile/SblIntegration/SWIFT_CODE_ARCH_DIR
export EMAIL_SERVER=172.20.10.151:25
*/
}